/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/magickwand-js.h"

/* Class: Geometry (_Magick_Geometry) */
// jsnapi_getclass
Napi::Function _Magick_Geometry_inst::GetClass(Napi::Env env) {
  std::map<std::string, _Magick_Geometry_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_Magick_Geometry_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_Magick_Geometry_inst>::DefineClass(env, "Geometry", symbolTable);
}

void _Magick_Geometry_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _Magick_Geometry_templ::PropertyDescriptor> &members,
  std::map<std::string, _Magick_Geometry_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("toString");
  members.insert({
    "toString",
      _Magick_Geometry_templ::InstanceMethod("toString",
        &_Magick_Geometry_templ::_wrap_Magick_Geometry_toString,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("aspect");
  members.insert({
    "aspect",
      _Magick_Geometry_templ::InstanceMethod("aspect",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_aspect,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("fillArea");
  members.insert({
    "fillArea",
      _Magick_Geometry_templ::InstanceMethod("fillArea",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_fillArea,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("greater");
  members.insert({
    "greater",
      _Magick_Geometry_templ::InstanceMethod("greater",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_greater,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("height");
  members.insert({
    "height",
      _Magick_Geometry_templ::InstanceMethod("height",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_height,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isValid");
  members.insert({
    "isValid",
      _Magick_Geometry_templ::InstanceMethod("isValid",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_isValid,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("less");
  members.insert({
    "less",
      _Magick_Geometry_templ::InstanceMethod("less",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_less,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("limitPixels");
  members.insert({
    "limitPixels",
      _Magick_Geometry_templ::InstanceMethod("limitPixels",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_limitPixels,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("percent");
  members.insert({
    "percent",
      _Magick_Geometry_templ::InstanceMethod("percent",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_percent,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("width");
  members.insert({
    "width",
      _Magick_Geometry_templ::InstanceMethod("width",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_width,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("xOff");
  members.insert({
    "xOff",
      _Magick_Geometry_templ::InstanceMethod("xOff",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_xOff,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("yOff");
  members.insert({
    "yOff",
      _Magick_Geometry_templ::InstanceMethod("yOff",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_yOff,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("clone");
  members.insert({
    "clone",
      _Magick_Geometry_templ::InstanceMethod("clone",
        &_Magick_Geometry_templ::_wrap_Geometry__wrap_Magick_Geometry_clone,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

