/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/magickwand-js.h"

/* Class: PathCurvetoArgs (_Magick_PathCurvetoArgs) */
// jsnapi_getclass
Napi::Function _Magick_PathCurvetoArgs_inst::GetClass(Napi::Env env) {
  std::map<std::string, _Magick_PathCurvetoArgs_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_Magick_PathCurvetoArgs_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_Magick_PathCurvetoArgs_inst>::DefineClass(env, "PathCurvetoArgs", symbolTable);
}

void _Magick_PathCurvetoArgs_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _Magick_PathCurvetoArgs_templ::PropertyDescriptor> &members,
  std::map<std::string, _Magick_PathCurvetoArgs_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("x1");
  members.insert({
    "x1",
      _Magick_PathCurvetoArgs_templ::InstanceMethod("x1",
        &_Magick_PathCurvetoArgs_templ::_wrap_PathCurvetoArgs__wrap_Magick_PathCurvetoArgs_x1,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("y1");
  members.insert({
    "y1",
      _Magick_PathCurvetoArgs_templ::InstanceMethod("y1",
        &_Magick_PathCurvetoArgs_templ::_wrap_PathCurvetoArgs__wrap_Magick_PathCurvetoArgs_y1,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("x2");
  members.insert({
    "x2",
      _Magick_PathCurvetoArgs_templ::InstanceMethod("x2",
        &_Magick_PathCurvetoArgs_templ::_wrap_PathCurvetoArgs__wrap_Magick_PathCurvetoArgs_x2,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("y2");
  members.insert({
    "y2",
      _Magick_PathCurvetoArgs_templ::InstanceMethod("y2",
        &_Magick_PathCurvetoArgs_templ::_wrap_PathCurvetoArgs__wrap_Magick_PathCurvetoArgs_y2,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("x");
  members.insert({
    "x",
      _Magick_PathCurvetoArgs_templ::InstanceMethod("x",
        &_Magick_PathCurvetoArgs_templ::_wrap_PathCurvetoArgs__wrap_Magick_PathCurvetoArgs_x,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("y");
  members.insert({
    "y",
      _Magick_PathCurvetoArgs_templ::InstanceMethod("y",
        &_Magick_PathCurvetoArgs_templ::_wrap_PathCurvetoArgs__wrap_Magick_PathCurvetoArgs_y,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

