/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/* ---------------------------------------------------------------------------
 * SWIG Node-API runtime : module exports
 *
 * This file provdes named exports for both CommonJS and ECMAScript 6
 *
 * ---------------------------------------------------------------------------*/

var dll = require('../lib/index.cjs');
var {
  MagickLibVersion,
  MagickLibAddendum,
  MagickMaximumValue,
  MagickMinimumValue,
  Magick_CoderInfo_header,
  MagickLibInterface,
  NAPI_VERSION,
  MagickppLibMinInterface,
  MagickLibMinInterface,
  MagickGitRevision,
  MagickppLibVersionText,
  MagickLibVersionText,
  MagickPlatform,
  MagickCore,
  MagickAuthoritativeLicense,
  MagickVersion,
  MagickOffsetFormat,
  MagickppLibAddendum,
  MagickQuantumDepth,
  MagickEpsilon,
  MagickPathExtent,
  MagickWandSignature,
  MagickSizeFormat,
  MagickReleaseDate,
  MagickLogFilename,
  MagickHDRISupport,
  MagickMinBufferExtent,
  MagickPackageName,
  MagickCopyright,
  MagickMaxBufferExtent,
  MagickQuantumRange,
  MagickppLibInterface,
  MagickTimeExtent,
  MagickHomeURL,
  MagickAuthoritativeURL,
  std,
  Magick,
  MagickCoreSignature,
} = dll;

module.exports = {
  MagickLibVersion,
  MagickLibAddendum,
  MagickMaximumValue,
  MagickMinimumValue,
  Magick_CoderInfo_header,
  MagickLibInterface,
  NAPI_VERSION,
  MagickppLibMinInterface,
  MagickLibMinInterface,
  MagickGitRevision,
  MagickppLibVersionText,
  MagickLibVersionText,
  MagickPlatform,
  MagickCore,
  MagickAuthoritativeLicense,
  MagickVersion,
  MagickOffsetFormat,
  MagickppLibAddendum,
  MagickQuantumDepth,
  MagickEpsilon,
  MagickPathExtent,
  MagickWandSignature,
  MagickSizeFormat,
  MagickReleaseDate,
  MagickLogFilename,
  MagickHDRISupport,
  MagickMinBufferExtent,
  MagickPackageName,
  MagickCopyright,
  MagickMaxBufferExtent,
  MagickQuantumRange,
  MagickppLibInterface,
  MagickTimeExtent,
  MagickHomeURL,
  MagickAuthoritativeURL,
  std,
  Magick,
  MagickCoreSignature,
};
