/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/magickwand-js.h"

/* Class: ReadOptions (_Magick_ReadOptions) */
// jsnapi_getclass
Napi::Function _Magick_ReadOptions_inst::GetClass(Napi::Env env) {
  std::map<std::string, _Magick_ReadOptions_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_Magick_ReadOptions_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_Magick_ReadOptions_inst>::DefineClass(env, "ReadOptions", symbolTable);
}

void _Magick_ReadOptions_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _Magick_ReadOptions_templ::PropertyDescriptor> &members,
  std::map<std::string, _Magick_ReadOptions_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("density");
  members.insert({
    "density",
      _Magick_ReadOptions_templ::InstanceMethod("density",
        &_Magick_ReadOptions_templ::_wrap_ReadOptions__wrap_Magick_ReadOptions_density,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("depth");
  members.insert({
    "depth",
      _Magick_ReadOptions_templ::InstanceMethod("depth",
        &_Magick_ReadOptions_templ::_wrap_ReadOptions__wrap_Magick_ReadOptions_depth,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("ping");
  members.insert({
    "ping",
      _Magick_ReadOptions_templ::InstanceMethod("ping",
        &_Magick_ReadOptions_templ::_wrap_ReadOptions__wrap_Magick_ReadOptions_ping,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("quiet");
  members.insert({
    "quiet",
      _Magick_ReadOptions_templ::InstanceMethod("quiet",
        &_Magick_ReadOptions_templ::_wrap_ReadOptions__wrap_Magick_ReadOptions_quiet,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("size");
  members.insert({
    "size",
      _Magick_ReadOptions_templ::InstanceMethod("size",
        &_Magick_ReadOptions_templ::_wrap_ReadOptions__wrap_Magick_ReadOptions_size,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("imageInfo");
  members.insert({
    "imageInfo",
      _Magick_ReadOptions_templ::InstanceMethod("imageInfo",
        &_Magick_ReadOptions_templ::_wrap_Magick_ReadOptions_imageInfo,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

