/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/magickwand-js.h"

/* Class: PathArcArgs (_Magick_PathArcArgs) */
// jsnapi_getclass
Napi::Function _Magick_PathArcArgs_inst::GetClass(Napi::Env env) {
  std::map<std::string, _Magick_PathArcArgs_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_Magick_PathArcArgs_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_Magick_PathArcArgs_inst>::DefineClass(env, "PathArcArgs", symbolTable);
}

void _Magick_PathArcArgs_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _Magick_PathArcArgs_templ::PropertyDescriptor> &members,
  std::map<std::string, _Magick_PathArcArgs_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("radiusX");
  members.insert({
    "radiusX",
      _Magick_PathArcArgs_templ::InstanceMethod("radiusX",
        &_Magick_PathArcArgs_templ::_wrap_PathArcArgs__wrap_Magick_PathArcArgs_radiusX,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("radiusY");
  members.insert({
    "radiusY",
      _Magick_PathArcArgs_templ::InstanceMethod("radiusY",
        &_Magick_PathArcArgs_templ::_wrap_PathArcArgs__wrap_Magick_PathArcArgs_radiusY,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("xAxisRotation");
  members.insert({
    "xAxisRotation",
      _Magick_PathArcArgs_templ::InstanceMethod("xAxisRotation",
        &_Magick_PathArcArgs_templ::_wrap_PathArcArgs__wrap_Magick_PathArcArgs_xAxisRotation,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("largeArcFlag");
  members.insert({
    "largeArcFlag",
      _Magick_PathArcArgs_templ::InstanceMethod("largeArcFlag",
        &_Magick_PathArcArgs_templ::_wrap_PathArcArgs__wrap_Magick_PathArcArgs_largeArcFlag,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("sweepFlag");
  members.insert({
    "sweepFlag",
      _Magick_PathArcArgs_templ::InstanceMethod("sweepFlag",
        &_Magick_PathArcArgs_templ::_wrap_PathArcArgs__wrap_Magick_PathArcArgs_sweepFlag,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("x");
  members.insert({
    "x",
      _Magick_PathArcArgs_templ::InstanceMethod("x",
        &_Magick_PathArcArgs_templ::_wrap_PathArcArgs__wrap_Magick_PathArcArgs_x,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("y");
  members.insert({
    "y",
      _Magick_PathArcArgs_templ::InstanceMethod("y",
        &_Magick_PathArcArgs_templ::_wrap_PathArcArgs__wrap_Magick_PathArcArgs_y,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

