/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/magickwand-js.h"

/* Class: coderInfoArray (_std_coderInfoArray) */
// jsnapi_getclass
Napi::Function _std_coderInfoArray_inst::GetClass(Napi::Env env) {
  std::map<std::string, _std_coderInfoArray_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_std_coderInfoArray_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_std_coderInfoArray_inst>::DefineClass(env, "coderInfoArray", symbolTable);
}

void _std_coderInfoArray_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _std_coderInfoArray_templ::PropertyDescriptor> &members,
  std::map<std::string, _std_coderInfoArray_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("size");
  members.insert({
    "size",
      _std_coderInfoArray_templ::InstanceMethod("size",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_size,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("capacity");
  members.insert({
    "capacity",
      _std_coderInfoArray_templ::InstanceMethod("capacity",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_capacity,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("reserve");
  members.insert({
    "reserve",
      _std_coderInfoArray_templ::InstanceMethod("reserve",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_reserve,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isEmpty");
  members.insert({
    "isEmpty",
      _std_coderInfoArray_templ::InstanceMethod("isEmpty",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_isEmpty,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("clear");
  members.insert({
    "clear",
      _std_coderInfoArray_templ::InstanceMethod("clear",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_clear,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("add");
  members.insert({
    "add",
      _std_coderInfoArray_templ::InstanceMethod("add",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_add,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("get");
  members.insert({
    "get",
      _std_coderInfoArray_templ::InstanceMethod("get",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_get,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("set");
  members.insert({
    "set",
      _std_coderInfoArray_templ::InstanceMethod("set",
        &_std_coderInfoArray_templ::_wrap_std_coderInfoArray_set,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

