name: Development CI

on:
  workflow_dispatch:
  push:
    branches: '*'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
  pull_request:
    branches: main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

jobs:

  swig:
    name: Generate the SWIG wrappers
    uses:
      ./.github/workflows/swig.yml

  debug-asan:
    runs-on: ubuntu-22.04
    needs: swig

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Download the SWIG-generated wrappers
        uses: actions/download-artifact@v8
        with:
          name: swig
          path: swig
      - name: Install the dependencies
        run: npm install --magickwand_js-skip-native --magickwand_js-skip-wasm
      - name: Install the xpacks
        run: npx xpm install
      - name: Get conan home
        shell: bash
        id: conan_home
        run: |
          npx xpm run -q conan -- version
          echo path=`npx xpm run -q conan -- config home` >> $GITHUB_OUTPUT
      - name: Cache conan artifacts
        id: conan-artifacts
        uses: actions/cache@v5
        with:
          path: ${{ steps.conan_home.outputs.path }}
          key: linux-debug-asan-conan
      - name: Install fonts on Ubuntu
        run: sudo apt-get install -y fonts-ubuntu || true
      - name: Build with ASAN
        run: |
          npx xpm install
          npx xpm run prepare --config native-debug
          npx xpm run configure --config native-debug -- -Db_sanitize=address
          npx xpm run build --config native-debug
        env:
          npm_config_enable_conan: true
      - name: Get ASAN library name
        id: asan-lib
        run: echo LD_PRELOAD=$(gcc -print-file-name=libasan.so) >> $GITHUB_OUTPUT
      - run: node ../node_modules/mocha/bin/mocha.js  -i -g Security --repeats 100 node.test.ts
        working-directory: ${{ github.workspace }}/test
        env:
          LSAN_OPTIONS: suppressions=${{ github.workspace }}/test/napi-leaks-suppression.txt
          LD_PRELOAD: ${{ steps.asan-lib.outputs.LD_PRELOAD }}
