name: Node.js CI

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'
  pull_request:
    branches: main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  prebuild-install:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: 
          - macos-12
          - macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install --skip-magickwand-wasm --skip-magickwand-native
      - run: |
          cd test/integration/browser-react-ts
          while true; do                                                    \
            rm -rf node_modules package-lock.json  ;                        \
            npm install --verbose --foreground-scripts magickwand.js@next ; \
          done
